"""modified unlock v2

Revision ID: 35ca7a9dc3a3
Revises: ee75e33e7c80
Create Date: 2026-01-11 22:34:38.932658

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "35ca7a9dc3a3"
down_revision: Union[str, Sequence[str], None] = "ee75e33e7c80"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("unlocks", sa.Column("id", sa.Uuid(), nullable=False))
    op.create_index(
        op.f("ix_unlocks_landmark_id"), "unlocks", ["landmark_id"], unique=False
    )
    op.create_index(op.f("ix_unlocks_user_id"), "unlocks", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_unlocks_user_id"), table_name="unlocks")
    op.drop_index(op.f("ix_unlocks_landmark_id"), table_name="unlocks")
    op.drop_column("unlocks", "id")
    # ### end Alembic commands ###
