"""Create Attempt

Revision ID: 5ae3b046861f
Revises: 8c79c08c0b0d
Create Date: 2026-01-11 11:30:18.383138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ae3b046861f'
down_revision: Union[str, Sequence[str], None] = '8c79c08c0b0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('landmark_id', sa.Uuid(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='attemptstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['landmark_id'], ['landmarks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_attempt_landmark_created_at', 'attempts', ['landmark_id', 'created_at'], unique=False)
    op.create_index('idx_attempt_landmark_status', 'attempts', ['landmark_id', 'status'], unique=False)
    op.create_index('idx_attempt_status_created_at', 'attempts', ['status', 'created_at'], unique=False)
    op.create_index('idx_attempt_user_created_at', 'attempts', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_attempt_user_status', 'attempts', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_attempts_landmark_id'), 'attempts', ['landmark_id'], unique=False)
    op.create_index(op.f('ix_attempts_user_id'), 'attempts', ['user_id'], unique=False)
    op.add_column('unlocks', sa.Column('attempt_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_unlocks_attempt_id'), 'unlocks', ['attempt_id'], unique=False)
    op.create_foreign_key(None, 'unlocks', 'attempts', ['attempt_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unlocks', type_='foreignkey')
    op.drop_index(op.f('ix_unlocks_attempt_id'), table_name='unlocks')
    op.drop_column('unlocks', 'attempt_id')
    op.drop_index(op.f('ix_attempts_user_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_landmark_id'), table_name='attempts')
    op.drop_index('idx_attempt_user_status', table_name='attempts')
    op.drop_index('idx_attempt_user_created_at', table_name='attempts')
    op.drop_index('idx_attempt_status_created_at', table_name='attempts')
    op.drop_index('idx_attempt_landmark_status', table_name='attempts')
    op.drop_index('idx_attempt_landmark_created_at', table_name='attempts')
    op.drop_table('attempts')
    # ### end Alembic commands ###
