"""Add profile_picture_path to users

Revision ID: 674880dd2e9b
Revises: f10456b44139
Create Date: 2025-12-09 18:24:48.793982

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "674880dd2e9b"
down_revision: Union[str, Sequence[str], None] = "f10456b44139"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "profile_picture_path",
            sa.String(),
            nullable=True,
            comment="Path to profile picture in MinIO storage",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "profile_picture_path")
    # ### end Alembic commands ###
