"""update_landmark_hint_and_photo_locations

Revision ID: 770ec9ac9cab
Revises: 8c79c08c0b0d
Create Date: 2025-12-16 17:09:44.534031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision: str = '770ec9ac9cab'
down_revision: Union[str, Sequence[str], None] = '8c79c08c0b0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('landmark_photo_locations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('landmark_id', sa.Uuid(), nullable=False),
    sa.Column('location', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('radius_meters', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['landmark_id'], ['landmarks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_landmark_photo_locations_location', 'landmark_photo_locations', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_landmark_photo_locations_landmark_id'), 'landmark_photo_locations', ['landmark_id'], unique=False)
    op.add_column('landmarks', sa.Column('hint_image_urls', sa.ARRAY(sa.String()), nullable=True))
    op.drop_geospatial_index(op.f('idx_landmarks_photo_location'), table_name='landmarks', postgresql_using='gist', column_name='photo_location')
    op.drop_geospatial_column('landmarks', 'photo_location')
    op.drop_column('landmarks', 'hint_image_url')
    op.drop_column('landmarks', 'photo_location_radius')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landmarks', sa.Column('photo_location_radius', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('landmarks', sa.Column('hint_image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_geospatial_column('landmarks', sa.Column('photo_location', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), autoincrement=False, nullable=True))
    op.create_geospatial_index(op.f('idx_landmarks_photo_location'), 'landmarks', ['photo_location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.drop_column('landmarks', 'hint_image_urls')
    op.drop_index(op.f('ix_landmark_photo_locations_landmark_id'), table_name='landmark_photo_locations')
    op.drop_geospatial_index('idx_landmark_photo_locations_location', table_name='landmark_photo_locations', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('landmark_photo_locations')
    # ### end Alembic commands ###
