"""create area table

Revision ID: 85232897085c
Revises: eecd305c23a4
Create Date: 2025-10-29 09:34:37.066693

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "85232897085c"
down_revision: Union[str, Sequence[str], None] = "eecd305c23a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "areas",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("parent_area_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.Column("badge_url", sa.String(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_area_id"], ["areas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_area_creator_verified",
        "areas",
        ["created_by", "is_verified"],
        unique=False,
    )
    op.create_index(
        "idx_area_parent_verified",
        "areas",
        ["parent_area_id", "is_verified"],
        unique=False,
    )
    op.create_index(op.f("ix_areas_created_by"), "areas", ["created_by"], unique=False)
    op.create_index(
        op.f("ix_areas_is_verified"), "areas", ["is_verified"], unique=False
    )
    op.create_index(
        op.f("ix_areas_parent_area_id"), "areas", ["parent_area_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_areas_parent_area_id"), table_name="areas")
    op.drop_index(op.f("ix_areas_is_verified"), table_name="areas")
    op.drop_index(op.f("ix_areas_created_by"), table_name="areas")
    op.drop_index("idx_area_parent_verified", table_name="areas")
    op.drop_index("idx_area_creator_verified", table_name="areas")
    op.drop_table("areas")
    # ### end Alembic commands ###
