"""add_landmark_hint_and_photo_location

Revision ID: 8c79c08c0b0d
Revises: 674880dd2e9b
Create Date: 2025-12-16 16:47:59.956482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision: str = '8c79c08c0b0d'
down_revision: Union[str, Sequence[str], None] = '674880dd2e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landmarks', sa.Column('hint_image_url', sa.String(), nullable=True))
    op.add_geospatial_column('landmarks', sa.Column('photo_location', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True))
    op.add_column('landmarks', sa.Column('photo_location_radius', sa.Integer(), nullable=True))
    op.create_geospatial_index('idx_landmarks_photo_location', 'landmarks', ['photo_location'], unique=False, postgresql_using='gist', postgresql_ops={})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index('idx_landmarks_photo_location', table_name='landmarks', postgresql_using='gist', column_name='photo_location')
    op.drop_column('landmarks', 'photo_location_radius')
    op.drop_geospatial_column('landmarks', 'photo_location')
    op.drop_column('landmarks', 'hint_image_url')
    # ### end Alembic commands ###
