"""fix attempt

Revision ID: e99b5e1a5a73
Revises: 5ae3b046861f
Create Date: 2026-01-11 11:33:35.565548

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e99b5e1a5a73"
down_revision: Union[str, Sequence[str], None] = "5ae3b046861f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_attempts_landmark_id"), table_name="attempts")
    op.drop_index(op.f("ix_attempts_user_id"), table_name="attempts")
    op.drop_index(op.f("ix_unlocks_attempt_id"), table_name="unlocks")
    op.create_index(
        op.f("ix_unlocks_attempt_id"), "unlocks", ["attempt_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_unlocks_attempt_id"), table_name="unlocks")
    op.create_index(
        op.f("ix_unlocks_attempt_id"), "unlocks", ["attempt_id"], unique=False
    )
    op.create_index(op.f("ix_attempts_user_id"), "attempts", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_attempts_landmark_id"), "attempts", ["landmark_id"], unique=False
    )
    # ### end Alembic commands ###
