"""modified unlock

Revision ID: ee75e33e7c80
Revises: e99b5e1a5a73
Create Date: 2026-01-11 13:00:00.346401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee75e33e7c80'
down_revision: Union[str, Sequence[str], None] = 'e99b5e1a5a73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempts', sa.Column('similarity_score', sa.Float(), nullable=True))
    op.add_column('attempts', sa.Column('error_message', sa.String(), nullable=True))
    op.alter_column('attempts', 'status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='attemptstatus', native_enum=False),
               existing_nullable=False)
    op.add_column('unlocks', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('idx_unlock_area_landmark'), table_name='unlocks')
    op.drop_index(op.f('idx_unlock_area_unlocked_at'), table_name='unlocks')
    op.drop_constraint(op.f('unlocks_area_id_fkey'), 'unlocks', type_='foreignkey')
    op.drop_column('unlocks', 'area_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unlocks', sa.Column('area_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('unlocks_area_id_fkey'), 'unlocks', 'areas', ['area_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_unlock_area_unlocked_at'), 'unlocks', ['area_id', 'unlocked_at'], unique=False)
    op.create_index(op.f('idx_unlock_area_landmark'), 'unlocks', ['area_id', 'landmark_id'], unique=False)
    op.drop_column('unlocks', 'updated_at')
    op.alter_column('attempts', 'status',
               existing_type=sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='attemptstatus', native_enum=False),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    op.drop_column('attempts', 'error_message')
    op.drop_column('attempts', 'similarity_score')
    # ### end Alembic commands ###
